# Generated by Django 4.2.6 on 2024-02-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series_reference', models.CharField(max_length=100)),
                ('Period', models.DateField()),
                ('Data_value', models.BigIntegerField()),
                ('Suppressed', models.CharField(max_length=100)),
                ('STATUS', models.CharField(max_length=100)),
                ('UNITS', models.CharField(max_length=30)),
                ('Magnitude', models.IntegerField()),
                ('Subject', models.CharField(max_length=200)),
                ('Group', models.CharField(max_length=200)),
                ('Series_title_1', models.CharField(max_length=200)),
                ('Series_title_2', models.CharField(max_length=200)),
                ('Series_title_3', models.CharField(max_length=200)),
            ],
        ),
    ]
